version: '3.8'

services:
  # ChromaDB Vector Database
  chroma:
    image: chromadb/chroma:latest
    container_name: ad_checker_chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=*
      - ALLOW_RESET=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ad-checker-network

  # Next.js Web Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ad_checker_web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CHROMA_URL=http://chroma:8000
    depends_on:
      chroma:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ad-checker-network

volumes:
  chroma-data:
    driver: local

networks:
  ad-checker-network:
    driver: bridge
